# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/heera/early_late_bitsync/early_late_bitsync.srcs/sources_1/bd/early_late_bd/ip/early_late_bd_zynq_ultra_ps_e_0_0/early_late_bd_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'early_late_bd_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/heera/early_late_bitsync/early_late_bitsync.srcs/sources_1/bd/early_late_bd/ip/early_late_bd_zynq_ultra_ps_e_0_0/early_late_bd_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'early_late_bd_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/heera/early_late_bitsync/early_late_bitsync.srcs/sources_1/bd/early_late_bd/ip/early_late_bd_zynq_ultra_ps_e_0_0/early_late_bd_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'early_late_bd_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/heera/early_late_bitsync/early_late_bitsync.srcs/sources_1/bd/early_late_bd/ip/early_late_bd_zynq_ultra_ps_e_0_0/early_late_bd_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'early_late_bd_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/heera/early_late_bitsync/early_late_bitsync.srcs/sources_1/bd/early_late_bd/ip/early_late_bd_zynq_ultra_ps_e_0_0/early_late_bd_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'early_late_bd_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/heera/early_late_bitsync/early_late_bitsync.srcs/sources_1/bd/early_late_bd/ip/early_late_bd_zynq_ultra_ps_e_0_0/early_late_bd_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'early_late_bd_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
