# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/early_late_bd/early_late_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==early_late_bd || ORIG_REF_NAME==early_late_bd} -quiet] -quiet

# IP: bd/early_late_bd/ip/early_late_bd_zynq_ultra_ps_e_0_0/early_late_bd_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==early_late_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==early_late_bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/early_late_bd/ip/early_late_bd_util_vector_logic_0_0/early_late_bd_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==early_late_bd_util_vector_logic_0_0 || ORIG_REF_NAME==early_late_bd_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/early_late_bd/ip/early_late_bd_early_late_bitsync_0_1/early_late_bd_early_late_bitsync_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==early_late_bd_early_late_bitsync_0_1 || ORIG_REF_NAME==early_late_bd_early_late_bitsync_0_1} -quiet] -quiet

# IP: bd/early_late_bd/ip/early_late_bd_xlconstant_0_0/early_late_bd_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==early_late_bd_xlconstant_0_0 || ORIG_REF_NAME==early_late_bd_xlconstant_0_0} -quiet] -quiet

# XDC: bd/early_late_bd/early_late_bd_ooc.xdc
